# Generated by Django 3.2.9 on 2021-11-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_name', models.FileField(upload_to='smile_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
