# Generated by Django 3.2.9 on 2021-11-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
