# Generated by Django 3.2.9 on 2021-11-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_data',
            field=models.ImageField(blank=True, max_length=999999, upload_to='message_image'),
        ),
    ]
